### ISSUE TITLE
TypeError: only size-1 arrays can be converted to Python scalars

### ISSUE THREAD

**Issue by ze-n-g** [THU-LYJ-Lab/DarkFeat#2]
when i run   python ./demo_darkfeat.py --input ./fig/DarkFeat/seq-01/ --output_dir ./output --resize 960 640 --model_path ./fig/DarkFeat/DarkFeat.pth

error:
Namespace(force_cpu=False, image_glob=['*.ARW'], input='./fig/DarkFeat/seq-01/', model_path='./fig/DarkFeat/DarkFeat.pth', output_dir='./output', resize=[960, 640])
Will resize to 960x640 (WxH)
Running inference on device "cuda"
Loaded DarkFeat model
==> Processing image directory input: ./fig/DarkFeat/seq-01/
==> Will write outputs to ./output
Traceback (most recent call last):
  File "./demo_darkfeat.py", line 108, in <module>
    E, inliers, pts1, pts2 = compute_essential(mkpts0, mkpts1, K)
  File "./demo_darkfeat.py", line 18, in compute_essential
    ransac_model, ransac_inliers = cv2.findEssentialMat(pts1, pts2, K_1, method=cv2.RANSAC, prob=0.999, threshold=0.001, maxIters=10000)
TypeError: only size-1 arrays can be converted to Python scalars

**Comment by ze-n-g** [comment]
I would really appreciate it if you could tell me which version of opencv you are using？

**Comment by hyz317** [comment]
Hi there,

The version I am currently utilizing is OpenCV 4.6.0.

**Comment by ze-n-g** [comment]
Thank you for your reply, I can't find the tourism dataset in GL3D's tourism_data.md, if it's convenient for you, please provide the link of the tourism dataset.
